### ISSUE TITLE
how to get data from liquipedia?

### ISSUE THREAD

**Issue by Jackie-LJQ** [Noxville/liquipedia_scripts#1]
Hello,
Could you please help me explain how you manage the parameter of you request.get() function? r = requests.get()

I want to get some data of cs players and analyse it on my own PC. I use code like this, 
res = requests.get('https://liquipedia.net/counterstrike/Portal:Players')
json = r.json()
But it has jsondecode error.

I am really new to python and api, sorry if the question is trival.
And thank you for your help.

**Comment by Noxville** [comment]
It's a media-wiki query. Check out https://www.mediawiki.org/wiki/API:Query

**Comment by Jackie-LJQ** [comment]
Thank you so much. I got it.
